name: wsiradiomics
channels:
  - conda-forge
dependencies:
  - python=3.11.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-image
  - openslide
  - openslide-python
  - shapely
  - geopandas
  - pyvips
  - pip:
      - opencv-python-headless